services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  CountryPack\:
    resource: '../../src/'

  CountryPack\Contracts\StateNameMapperInterface:
    class: 'CountryPack\Mapper\StateEnglishNameMapper'

  CountryPack\Contracts\CountryCurrencyMapperInterface:
    class: 'CountryPack\Mapper\CountryCurrencyMapper'

  CountryPack\Contracts\CurrencyNameMapperInterface:
    class: 'CountryPack\Mapper\CurrencyEnglishNameMapper'

  CountryPack\Contracts\CurrencySignMapperInterface:
    class: 'CountryPack\Mapper\CurrencySignMapper'

  CountryPack\Contracts\CountryNameMapperInterface:
    class: 'CountryPack\Mapper\CountryEnglishNameMapper'

  CountryPack\Contracts\CountryDialCodeMapperInterface:
    class: 'CountryPack\Mapper\CountryDialCodeMapper'

  CountryPack\Contracts\CountryImageMapperInterface:
    class: 'CountryPack\Mapper\CountryImageMapper'

  CountryPack\Contracts\IsoCodeMapperInterface:
    class: 'CountryPack\Mapper\IsoCodeMapper'